spring:
  datasource:
    url: jdbc:mysql://lvyongwen-win.vmic.xyz:3306/example?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
debug: true
